name: vns
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python
  - pytables
  - xarray-datatree
  - pandas
  - ipykernel
  - pre-commit
  - ruff
  - plotly
  - nbformat
  - scipy
  - matplotlib
  - ipykernel
  - ydata-profiling
