name: vns
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - pytables>=3.8.0
  - pandas>=2.1.3
  - ipykernel>=6.25.0
  - scipy>=1.11.4
  - pre-commit>=2.20.0
  - pytest>=7.4.0
  - ruff>=0.1.6
  - pandera>=0.17.2
  - xarray-datatree
  - matplotlib>=3.8.0
