name: vns
channels:
  - conda-forge
dependencies:
  - python
  - xarray-datatree
  - pandas
  - zarr
  - ipympl
  - nbdev
  - ipykernel
  - pre-commit
  - ruff
  - scipy
  - matplotlib
  - ipywidgets
  - nbdev
  - dask
  - trame
  - plotly