name: .vns
channels:
  - cinpla
  - conda-forge
dependencies:
  - python>=3.10
  - pytables>=3.8.0
  - vaex-core>=4.17.1
  - vaex-hdf5>=0.14.1
  - vaex-jupyter>=0.8.1
  - vaex-viz>=0.5.4
  - exdir
  - pandas>=2.1.3
  - dash>=2.14.2
  - dash-bootstrap-components>=1.5.0
  - ipykernel>=6.25.0
  - scipy>=1.11.4
  - pre-commit>=2.20.0
  - pytest>=7.4.0
  - ruff>=0.1.6
  - pandera>=0.17.2
