name: vns
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - pytables>=3.8.0
  - pandas>=2.1.3
  - ipykernel>=1.0.0
  - pre-commit>=2.20.0
  - ruff>=0.1.6
  - plotly>=5.18.0
  - conda-lock
