name: vns
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python
  - pytables
  - xarray-datatree
  - pandas
  - nbformat
  - zarr
  - ipympl
  - hvplot
  - nbdev
  - ipykernel
  - pre-commit
  - ruff
  - plotly
  - scipy
  - matplotlib
  - ipywidgets
  - jupyter
  - "ydata-profiling[notebook]"
  - nbdev
  - dask
platforms:
  - linux-64
