[project]
name = "vns"
version = "0.1.0"
description = "Add a short description here"
authors = ["Ty Schlichenmeyer <ty.schlich@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
ipywidgets = ">=8.1.1,<8.2"
pandas = ">=2.1.4,<2.2"
ipykernel = ">=6.28.0,<6.29"
python = ">=3.12.1,<3.13"
scipy = ">=1.11.4,<1.12"
ruff = ">=0.1.9,<0.2"
pre-commit = ">=3.6.0,<3.7"
matplotlib = ">=3.8.2,<3.9"
xarray = ">=2023.12.0,<2023.13"
xarray-datatree = ">=0.0.13,<0.1"
plotly = ">=5.18.0,<5.19"
pyarrow = ">=14.0.2,<14.1"
zarr = ">=2.16.1,<2.17"
toolz = ">=0.12.0,<0.13"
dask = ">=2023.12.1,<2023.13"
hvplot = ">=0.9.1,<0.10"
seaborn = ">=0.13.0,<0.14"
polars = ">=0.20.2,<0.21"
pillow = ">=10.1.0,<10.2"
jupyter = ">=1.0.0,<1.1"
trame = ">=3.4.0,<3.5"
trame-vtk = ">=2.6.3,<2.7"
trame-plotly = ">=2.1.1,<2.2"
trame-vuetify = ">=2.3.1,<2.4"
vtk = ">=9.2.6,<9.3"
numpy = ">=1.26.2,<1.27"
pytest = ">=7.4.4,<7.5"
ipdb = ">=0.13.13,<0.14"
cmake = ">=3.28.1,<3.29"
tqdm = ">=4.66.1,<4.67"
jupyterlab = ">=4.0.10,<4.1"
nodejs = ">=20.9.0,<20.10"
cmasher = ">=1.7.2,<1.8"
pip = ">=23.3.2,<23.4"
mkdocstrings-python = ">=1.7.5,<1.8"
mkdocs-material = ">=9.3.1,<9.4"

[pypi-dependencies]
ratinabox = "*"
pandera = { version = "*", extras = ["mypy"] }
