[project]
name = "vns"
version = "0.1.0"
description = "Add a short description here"
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = ">=3.12.1"
scipy = ">=1.11.4"
icecream = ">=2.1.3"
python-graphviz = ">=0.20.1"
pip = ">=23.3.2"
ipython = ">=8.20.0"
dask = ">=2024.1.0"
ipywidgets = ">=8.1.1"
matplotlib = ">=3.8.2"
pandera = ">=0.18.0"
plotly = ">=5.18.0"
xarray = ">=2023.12.0"
ipykernel = ">=6.29.0"
shiny = ">=0.8.1"
