[project]
name = "vns"
version = "0.1.0"
license = { text = "GPL-3.0-or-later" }
readme = "README.md"
dependencies = [
    "ratinabox",
    "pandas",
    "pandera[mypy]",
    "plotly",
    "xarray",
    "seaborn",
    "shiny @ git+https://github.com/posit-dev/py-shiny",
    "htmltools @ git+https://github.com/posit-dev/py-htmltools",
    "polars",
    "pyarrow",
    "ipykernel",
    "hvplot",
    "xarray-datatree",
]
requires-python = ">=3.12"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.envs.vns.scripts]
dash = "shiny run app.py"


[tool.hatch.envs.test.scripts]
extra-dependencies = "pytest"
test = "pytest"

[tool.ruff]
ignore = [
    "ANN101",
    "ANN201",
    "ANN204",
    "D100",
    "D101",
    "D102",
    "D103",
    "D105",
    "D107",
    "S101",
]
extend-include = ["*.ipynb"]
fix = true
select = ["ALL"]

[tool.mypy]
plugins = "pandera.mypy"

[tool.pyright]
venvPath = ".hatch"
venv = "vns"
