[project]
name = "vns"
version = "0.1.0"
description = ""
authors = [{ name = "Ty Schlichenmeyer", email = "t.schlic@wustl.edu" }]
dependencies = ["plotly", "ipywidgets", "ruff>=0.1.4", "jupyter", "quarto"]
requires-python = ">=3.11,<3.12"
readme = "README.md"
license = { text = "MIT" }

[tool.ruff]
extend-include = ["*.ipynb"]
select = ["ALL"]
fix = true
