[project]
name = "vns"
version = "0.1.0"
license = { text = "GPL-3.0-or-later" }
readme = "README.md"
dependencies = ["ratinabox"]

[tool.ruff]
ignore = [
    "ANN101",
    "ANN201",
    "ANN204",
    "D100",
    "D101",
    "D102",
    "D103",
    "D105",
    "D107",
    "S101"
]
extend-include = ["*.ipynb"]
fix = true
select = ["ALL"]

[tool.setuptools]
packages = ["vns", "tests"]

[tool.mypy]
plugins = "pandera.mypy"