[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "vns"
version = "0.1.0"
license = { file = "LICENSE" }
readme = "README.md"

[tool.ruff]
extend-include = ["*.ipynb"]
fix = true
select = ["ALL"]

[tool.pyright]
venvPath = ".micromamba/envs"
venv = "vns"
