[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Ty Schlichenmeyer", email = "t.schlic@wustl.edu"},
]
dependencies = [
    "ipykernel>=6.26.0",
    "pandas>=2.1.0",
]
requires-python = ">=3.12,<3.13"
readme = "README.md"
license = {text = "MIT"}

