[project]
name = "vns"
version = "0.1.0"
description = ""
authors = [{ name = "Ty Schlichenmeyer", email = "t.schlic@wustl.edu" }]
dependencies = [
    "ruff>=0.1.4",
    "dash>=2.14.1",
    "dash-bootstrap-components>=1.5.0",
    "nbdev>=2.3.13",
    "pre-commit>=3.5.0",
    "jupyter>=1.0.0",
    "mat4py>=0.6.0",
    "dbt-duckdb>=1.7.0",
    "pandas>=2.1.3",
    "quarto",
    "pip-tools",
]
requires-python = ">=3.11,<3.12"
readme = "README.md"
license = { text = "MIT" }

[tool.ruff]
extend-include = ["*.ipynb"]
select = ["ALL"]
fix = true
