[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "vns"
version = "0.1.0"
license = { text = "GPL-3.0-or-later" }
readme = "README.md"

[tool.ruff]
extend-include = ["*.ipynb"]
fix = true
select = ["ALL"]
ignore = ["ANN101", "ANN201", "D100", "D102", "D103", "D105", "ANN204"]

[tool.pyright]
venvPath = ".pixi"
venv = "env"
