[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "vns"
version = "0.1.0"
description = "VNS analysis for the dissertation of Tyler Schlichenmeyer"
readme = "README.md"
license = "GPL-3.0-or-later"
requires-python = ">=3.10"
authors = [{ name = "Ty Schlichenmeyer", email = "tschlic@wustl.edu" }]
keywords = ["jupyter", "nbdev", "notebook", "python"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Natural Language :: English",
    "Programming Language :: Python :: 3.11",
]
dependencies = [
    "pandas>=2.1.3",
    "ipykernel>=6.25.0",
    "scipy>=1.11.4",
    "pre-commit>=2.20.0",
    "pytest>=7.4.0",
    "ruff>=0.1.6",
    "dash>=2.14.2",
    "dash-bootstrap-components>=1.5.0",
]

[project.urls]
Homepage = "https://github.com/schlich/vns"

[tool.hatch.version]
path = "vns/__init__.py"

[tool.ruff]
extend-include = ["*.ipynb"]
select = ["ALL"]
fix = true

[tool.ruff.per-file-ignores]
"**/*.ipynb" = ["D100"]
"tests/*.py" = ["S101", "D100", "D103", "ANN201"]
