ipynb-filters: [nbdev_filter]

project:
  type: website
  output-dir: _docs
  preview:
    port: 3000
    browser: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 4

website:
  title: "vns"
  site-url: "https://schlich.github.io/vns"
  description: "Data analysis for a VNS conditioned stimulus extinction task"
  twitter-card: true
  open-graph: true
  repo-branch: main
  repo-url: "https://github.com/schlich/vns"
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: "https://github.com/schlich/vns"
  sidebar:
    style: "floating"

metadata-files: 
  - sidebar.yml
  - custom.yml
