# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/vns',
                'doc_host': 'https://schlich.github.io',
                'git_url': 'https://github.com/schlich/vns',
                'lib_path': 'vns'},
  'syms': {'vns.core': {'vns.core.foo': ('core.html#foo', 'vns/core.py')}}}
