# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['sessions', 'session']

# %% ../nbs/00_core.ipynb 5
def sessions(data_dir: str) -> xr.Dataset:
    """Retrieve session data as a DataFrame."""
    data_home = Path(os.environ["XDG_DATA_HOME"])
    filenames = data_home / data_dir
    filepaths = filenames.glob("*.mat")
    return pd.DataFrame.from_records(
        [session_attrs(filepath) for filepath in filepaths],
        index=dt_index_from_data_dir(filenames),
    ).to_xarray()


def session(mat_file: Path) -> xr.DataArray:
    """Retrieve session data as a DataArray."""
    return xr.DataArray.from_dict(session_attrs(mat_file))
