# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_session.ipynb.

# %% auto 0
__all__ = ['Session']

# %% ../nbs/00_session.ipynb 2
from pathlib import Path

import pandas as pd
import plotly.express as px
import scipy


class Session:
    """A group of consecutive trials."""

    def __init__(self, matfile_path: Path):
        self.data = scipy.io.loadmat(
            matfile_path,
            squeeze_me=True,
        )["PDS"]

    def eyejoy(self):
        eyejoy_data = pd.DataFrame.from_records(self.data["EyeJoy"].item()).rename(
            columns={0: "x", 1: "y", 4: "t"},
        )
        eyejoy_data.index.name = "trial"
        return eyejoy_data[["x", "y", "t"]].explode(column=["x", "y", "t"])

    def __repr__(self):
        return px.line(self.data, x="t", y=["x", "y"])
