# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_trial.ipynb.

# %% auto 0
__all__ = ['Trial']

# %% ../nbs/00_trial.ipynb 2
from .session import Session


class Trial:
    def __init__(self, session: Session, trial_num: int):
        self.eyejoy = session.eyejoy.sel(trial=trial_num)
